### ISSUE TITLE
FirebaseApp not initialized with the latest Xamarin.Azure.NotificationHubs.Android binding

### ISSUE THREAD

**Issue by andrekiba** [Azure/azure-notificationhubs-xamarin#49]
This issue is related to #21 
With the latest version of the `Xamarin.Azure.NotificationHubs.Android ` binding (1.1.4.1) we have exactly the same error.
Sorry @marstr but I really don't understand at this point.
Is it possibile to have something that works?
Or at least have a support to understand the problem, I asked many times to have the possibility to schedule a call, with you or I don't know with who.
After two months we are more or less at the same point, nothing that works as AppCenter.Push before.

```
Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process. Make sure to call FirebaseApp.initializeApp(Context) first.
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticVoidMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeVoidMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at WindowsAzure.Messaging.NotificationHubs.NotificationHub.Start (Android.App.Application application, System.String hubName, System.String connectionString) [0x00068] in <3b91ec8468704611bcbe892fa8e0255b>:0 
  at Elfo.Ambrogio.App.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x000e1] in /Volumes/bahamut/projects/Elfo/Elfo/Elfo.Ambrogio/App/Elfo.Ambrogio.App.Android/MainActivity.cs:74 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <84ca7e914f6148f0b961431a9ac4287b>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.16(intptr,intptr,intptr)
  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process net.elfo.ambrogio. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
	at com.google.firebase.messaging.FirebaseMessaging.getInstance(com.google.firebase:firebase-messaging@@21.0.1:1)
	at com.microsoft.windowsazure.messaging.notificationhubs.NotificationHubExtension.fetchPushChannel(NotificationHubExtension.java:33)
	at com.microsoft.windowsazure.messaging.notificationhubs.NotificationHub.registerApplication(NotificationHub.java:95)
	at com.microsoft.windowsazure.messaging.notificationhubs.NotificationHub.start(NotificationHub.java:132)
	at com.microsoft.windowsazure.messaging.notificationhubs.NotificationHub.start(NotificationHub.java:115)
	at net.elfo.ambrogio.MainActivity.n_onCreate(Native Method)
	at net.elfo.ambrogio.MainActivity.onCreate(MainActivity.java:40)
	at android.app.Activity.performCreate(Activity.java:7023)
	at android.app.Activity.performCreate(Activity.java:7014)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by marstr** [comment]
Thanks for creating a new thread, @andrekiba.

Please try the solution seen here: https://stackoverflow.com/questions/49452001/default-firebaseapp-is-not-initialized-in-this-process-make-sure-to-call-fireba?fbclid=IwAR1rc8Bx6dRctfb2lYAg_NrtZKF6X4ib0jloul6ic4dbcr3hCc7z9M18AQE

**Comment by andrekiba** [comment]
already tried @marstr, exactly your link...doesn't work.
You have the google-services.json of out app. 
about the guide here https://docs.microsoft.com/it-it/azure/notification-hubs/xamarin-notification-hubs-push-notifications-android-gcm
what is still useful and what not?

**Comment by andrekiba** [comment]
Looking at this https://forums.xamarin.com/discussion/181872/firebase-app-giving-default-firebaseapp-is-not-initialized-in-this-process-error I also tried to add directly the `Xamarin.Firebase.Messaging` v121.0.1  and `Xamarin.GooglePlayServices.Base` v117.5.0 to the Android project.
The two packages with the same versions are also referenced from your project as follow:
```
<PackageReference Include="Xamarin.Azure.NotificationHubs.Android" Version="1.1.4.1" />
<PackageReference Include="Xamarin.Android.Volley" Version="1.1.1.1" />
<PackageReference Include="Xamarin.Firebase.Messaging" Version="121.0.1" />
<PackageReference Include="Xamarin.GooglePlayServices.Base" Version="117.5.0" />
<PackageReference Include="Xamarin.GooglePlayServices.Iid" Version="117.0.0" />
<PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.2.0.6" />
<PackageReference Include="Xamarin.AndroidX.Migration" Version="1.0.8" />
<PackageReference Include="Xamarin.Google.Android.DataTransport.TransportBackendCct" Version="2.3.3" />
<PackageReference Include="Xamarin.Google.Android.DataTransport.TransportRuntime" Version="2.2.5" />
```
In manifest the sdk version is
`<uses-sdk android:minSdkVersion="25" android:targetSdkVersion="29" />`

Doing this I have another beautiful exception starting the app.

```
Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/datatransport/runtime/dagger/internal/Factory; ---> Java.Lang.ClassNotFoundException: com.google.android.datatransport.runtime.dagger.internal.Factory ---> Java.Lang.NoClassDefFoundError: Failed resolution of: Ljavax/inject/Provider; ---> Java.Lang.ClassNotFoundException: Didn't find class "javax.inject.Provider" on path: DexPathList[[zip file "/data/app/net.elfo.ambrogio-uR7ZQtj7TUOHrvMAduWj7A==/base.apk"],nativeLibraryDirectories=[/data/app/net.elfo.ambrogio-uR7ZQtj7TUOHrvMAduWj7A==/lib/arm64, /data/app/net.elfo.ambrogio-uR7ZQtj7TUOHrvMAduWj7A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
  --- End of managed Java.Lang.NoClassDefFoundError stack trace ---
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/datatransport/runtime/dagger/internal/Factory;
	at com.google.android.datatransport.runtime.DaggerTransportRuntimeComponent.builder(DaggerTransportRuntimeComponent.java:70)
	at com.google.android.datatransport.runtime.TransportRuntime.initialize(TransportRuntime.java:76)
	at com.google.firebase.datatransport.TransportRegistrar.lambda$getComponents$0(TransportRegistrar.java:37)
	at com.google.firebase.datatransport.TransportRegistrar$$Lambda$1.create(Unknown Source:0)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
	at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
	at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
	at com.google.firebase.messaging.FirebaseMessagingRegistrar.lambda$getComponents$0$FirebaseMessagingRegistrar(Unknown Source:43)
	at com.google.firebase.messaging.FirebaseMessagingRegistrar$$Lambda$0.create(Unknown Source:0)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6263)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.ClassNotFoundException: com.google.android.datatransport.runtime.dagger.internal.Factory
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/inject/Provider;
	... 36 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.inject.Provider" on path: DexPathList[[zip file "/data/app/net.elfo.ambrogio-uR7ZQtj7TUOHrvMAduWj7A==/base.apk"],nativeLibraryDirectories=[/data/app/net.elfo.ambrogio-uR7ZQtj7TUOHrvMAduWj7A==/lib/arm64, /data/app/net.elfo.ambrogio-uR7ZQtj7TUOHrvMAduWj7A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 36 more
```

**Comment by andrekiba** [comment]
Referencing Xamarin.Google.Dagger in the Android project seems solve this https://stackoverflow.com/questions/65381403/java-lang-noclassdeffounderror-when-implementing-firebase-cloud-messaging.
Do you know the reason?

**Comment by marstr** [comment]
Interesting - there must be a transitive dependency that isn't getting communicated all the way through. We'll follow up with this before we release a NuGet package.

**Comment by marstr** [comment]
Doing some house-keeping. Because this is something that will get tidied up when we fix #38, I'm going to close it as a duplicate.

**Comment by FrankSzendzielarz** [comment]
I am getting this error too, with latest libraries. The original error. Even with the Dagger reference. I have tried adding the FirebaseApp.InitializeApp into OnCreate, but NotificationHub.Start always throws this error. At a loss how to proceed.

**Comment by adambarath** [comment]
I solved it by check all setting on Google Console and Firebase Console. (I had a unset policy settings..)

**Comment by FrankSzendzielarz** [comment]
Yes i finally found the root of the issue which for me was that the new Firebase stuff manages "installations" as a new API, so it's necessary to go into cloud console and enable Firebase Installation Api . Without this the device registration fails , which happens when the azure hub client is started.
